### ISSUE TITLE
Possible memory leak?

### ISSUE THREAD

**Issue by scientist1642** [ikostrikov/pytorch-a3c#11]
Training Breakout goes ok but, memory usage exceeds 25gb after 4 hours of training on 16 cpu cores.
I wonder if it's related to sharing memory between processes.

I run Python 3.5 on scientific linux.

**Comment by ikostrikov** [comment]
Hmm. At least not one that I can immediately find.

It makes sense to ask this question on discuss.pytorch.

**Comment by scientist1642** [comment]
Ok thanks, I also couldn't find something wrong with the code.
I asked it on [discuss](https://discuss.pytorch.org/t/memory-usage-of-a-python-process-increases-slowly/1355).
So you don't have a memory problem when you run it for hours right?

**Comment by ikostrikov** [comment]
I ran it on a machine with large amount of RAM, so I didn't even notice the problem :(

And luck identifying the leak? I've been trying to find it for days.

**Comment by ethancaballero** [comment]
Were you using pip install version or self-compiled version?
Has anyone A/B tested pip install version vs self-compiled version as suggested in https://discuss.pytorch.org/t/memory-usage-of-a-python-process-increases-slowly/1355/2
?

**Comment by ikostrikov** [comment]
I have tried both conda and pip versions. Both of them have this problem.

**Comment by scientist1642** [comment]
@ikostrikov same here, it's taking quite a time. Haven't found it yet. 
I didn't have problems with memory in python before, so at least I'm learning something :)

One note - it seems not related to multiprocessing as I initially thought. I don't use processes and removed LSTM cell in feedforward and the issue still there.
@ethancaballero  I also tried installing binaries with both, haven't tried self-compiled version yet.

**Comment by ethancaballero** [comment]
The self-compiled version is supposed to be more problematic, so maybe just stick with pip version for now.

**Comment by ethancaballero** [comment]
Maybe start ablating it until it looks like the example pytorch actor_critic implementation to see which component is causing the problem:
https://github.com/pytorch/examples/blob/master/reinforcement_learning/actor_critic.py

**Comment by ethancaballero** [comment]
Hmm, the example actor_critic.py implementation also suffers from memory leak.

However, the memory leak for it and this pytorch-a3c repo are reduced by ~10x if you upgrade pytorch to the most recent nightly build (I just tested it).
Uninstall previous pytorch and then run this command to get nightly build that reduces leak:
`pip3 install git+https://github.com/pytorch/pytorch`

I think the main fix that occurred in the recent nightly build is this commit:
https://github.com/pytorch/pytorch/commit/f531d98341d6c49f859ba21496f446c3189cb29d
in response to this issue:
https://discuss.pytorch.org/t/storing-torch-tensor-for-dqn-memory-issue/916/15

**Comment by ethancaballero** [comment]
Yay, memory stabilizes at 118408.0 mb with most recent nightly build (version '0.1.10+2fd4d08').

**Comment by ikostrikov** [comment]
Thanks! This one definitely helps.

**Comment by ikostrikov** [comment]
Ok. I have been running it for several hours. No signs of sever leaks anymore. Closing the issue. Thanks a lot!

**Comment by scientist1642** [comment]
Great, thanks! works for me as well.

**Comment by xmfbit** [comment]
@scientist1642 Hi, what vision have you used? My version is 0.1.12+0025e1c and memory leak problem is still here.

**Comment by scientist1642** [comment]
@xmfbit I worked on it before June, and several releases I installed after 0.1.10+2fd4d08 worked for me. Try a bit older version (like 0.11) maybe there is a bug in Pytorch again.
