### ISSUE TITLE
SharedAdam bias correction wrong

### ISSUE THREAD

**Issue by pfre00** [ikostrikov/pytorch-a3c#12]
The timestep parameters of the [SharedAdam](https://github.com/ikostrikov/pytorch-a3c/blob/master/my_optim.py) optimizer are not shared. This should lead to bias overcorrection, leading to incorrect unbiased estimates. Does the current implementation work?

**Comment by ikostrikov** [comment]
Yes, that's true. Thanks! I will fix it in the next couple of days.

**Comment by ikostrikov** [comment]
Fixed in
https://github.com/ikostrikov/pytorch-a3c/commit/5d9b07d80740e26f78cb283f74b5b802906a9d83
