### ISSUE TITLE
Removing Universe dependency

### ISSUE THREAD

**Issue by scientist1642** [ikostrikov/pytorch-a3c#16]
Universe has quite many dependencies including Go and here basically only gym is used.
Vectorized api is useful in some cases but  wrappers here just seem to replace and normalize observations. Or is it useful for some reason?
I replaced it with gym wrappers and everything looks fine.
[diff](https://github.com/scientist1642/pytorch-a3c/compare/master...scientist1642:dev#diff-13e6ea7229e5dcc10a580b33c20913fcR57)

**Comment by ikostrikov** [comment]
Thanks!
