### ISSUE TITLE
memory overflow

### ISSUE THREAD

**Issue by dylanthomas** [ikostrikov/pytorch-a3c#17]
I tried to run your code on my ubuntu/Titan-X/Intel i7, but I kept getting memory problems, after about one day.  Can you guess why ?
I tried both
OMP_NUM_THREADS=1 python main.py --env-name "Breakout-v0" --num-processes 8
and
OMP_NUM_THREADS=1 python main.py --env-name "Breakout-v0" --num-processes 6
, to see if bringing down num-processes might help.  But that did not work out either.

ps.  
(from free -m >> mem_usage.txt)
              total        used        free      shared  buff/cache   available
Mem:          64388       63937         325          14         125         271
Swap:         65451       65451           0
Fri Mar 31 17:55:18 KST 2017

**Comment by ikostrikov** [comment]
What version of PyTorch are you using?

**Comment by dylanthomas** [comment]
I just ran 'conda install pytorch torchvision cuda80 -c soumith'

**Comment by ikostrikov** [comment]
And what version it is? There was a problem with memory overflow in an earlier build of PyTorch.

**Comment by dylanthomas** [comment]
pytorch                   0.1.10               py35_1cu80  [cuda80]  soumith
(from conda list)

**Comment by ikostrikov** [comment]
Update PyTorch to the latest version.

**Comment by dylanthomas** [comment]
ok.  many thanks.
