### ISSUE TITLE
License of this repository?

### ISSUE THREAD

**Issue by kimhc6028** [ikostrikov/pytorch-a3c#18]
Thank you for this great repository.
I am implementing
[Curiosity-driven Exploration by Self-supervised Prediction](https://pathak22.github.io/noreward-rl/resources/icml17.pdf)
with pytorch, and this needs A3C.
I wish I could start it with your code, but I couldn't find any license of this repository. May I use codes in this repo for my implementation?

**Comment by ikostrikov** [comment]
Hi, I'm not good at licenses. Which one is a good one?

**Comment by AjayTalati** [comment]
The smallest one - http://www.wtfpl.net

**Comment by ikostrikov** [comment]
I think I'm going to add MIT license. Any objections?

**Comment by kimhc6028** [comment]
No objections. Many thanks!! :)

**Comment by ikostrikov** [comment]
The new license is in the repo.
