### ISSUE TITLE
question about using GAE

### ISSUE THREAD

**Issue by andrewliao11** [ikostrikov/pytorch-a3c#34]
I found that in original [GAE paper](https://arxiv.org/abs/1506.02438) 
eq.16 
A_{t}^{GAE} =  \sum_{l=0 }^{\infty} (\gamma \tau )^l \delta_{t+l}^{V} 

However, in the code the advantage is look like
https://github.com/ikostrikov/pytorch-a3c/blob/master/train.py#L97
```
gae = gae * args.gamma * args.tau + delta_t
```

Shouldn't it modified into:
```
gae += args.gamma * args.tau * delta_t
```

I haven't implemented code with GAE before, so I'm just curious about this

**Comment by ikostrikov** [comment]
Hi, I'm sorry for a late reply. In the original equation it's computed in a forward pass. While here it's computed in a backward pass.
