### ISSUE TITLE
 File "main.py", line 55,TypeError: sum received an invalid combination of arguments 

### ISSUE THREAD

**Issue by happykayy** [ikostrikov/pytorch-a3c#38]
File "main.py", line 55, in <module>
    env.observation_space.shape[0], env.action_space)
  File "/home/bruce/Downloads/pytorch-a3c-master/pytorch-a3c-master/model.py", line 47, in __init__
    self.actor_linear.weight.data, 0.01)
  File "/home/bruce/Downloads/pytorch-a3c-master/pytorch-a3c-master/model.py", line 9, in normalized_columns_initializer
    out *= std / torch.sqrt(out.pow(2).sum(1, keepdim=True))
TypeError: sum received an invalid combination of arguments - got (int, keepdim=bool), but expected one of:
 * no arguments
 * (int dim)

my environment is Ubuntu 14.04
I just run your code without change and the error comes out, please help,thanks

**Comment by ikostrikov** [comment]
What is the version of PyTorch that you are using?

print(torch.__version__)

**Comment by happykayy** [comment]
0.1.12

**Comment by ikostrikov** [comment]
Try to install the latest one. They changed API in 0.2.0.

**Comment by happykayy** [comment]
ok，thanks ！
