### ISSUE TITLE
Running with pytorch 0.2.0

### ISSUE THREAD

**Issue by ShaniGam** [ikostrikov/pytorch-a3c#40]
Have you tried running it with pytorch 0.2.0? seem like the multiprocessing doesn't work.

**Comment by ikostrikov** [comment]
Hi. Yes, I works for me for pytorch 0.2.0. What do you mean by mp doesn't work?

**Comment by ShaniGam** [comment]
all the training processes exit after:
`(policy_loss + args.value_loss_coef * value_loss).backward()`
in some cases I get a core file that says:
`Program terminated with signal 11, Segmentation fault.` but it doesn't say where it happened exactly
I did manage to run other python files using pytorch 0.2

**Comment by ShaniGam** [comment]
252 GB
it worked perfectly with pytorch 1.2 (but I have to upgrade)

**Comment by ikostrikov** [comment]
Does it happen immediately or after several hours of training?

What arguments do you use?

**Comment by ShaniGam** [comment]
Immediately, default arguments.

**Comment by ikostrikov** [comment]
Do you use python2 or python3?

At the moment, I cannot reproduce the issue. I need more information.

**Comment by ShaniGam** [comment]
python 2.7
I deleted all the torch files and installing it from scratch now, It might be a conflict between the versions (even though it does work on other files)

**Comment by ikostrikov** [comment]
This code works only for python 3. I'm not planning to add support for python 2 any time soon (it's already scheduled to be deprecated anyway).

**Comment by ShaniGam** [comment]
Oh, so that's why!
btw, thank you for the code, it's been very useful in my research :)
