### ISSUE TITLE
Where does the initializer come from?

### ISSUE THREAD

**Issue by zhengsx** [ikostrikov/pytorch-a3c#41]
Hi,

I found some initializers in [model.py](https://github.com/ikostrikov/pytorch-a3c/blob/master/model.py#L45-L54). The values are not very clearly to me. Could you please explain where does they come from and is that suitable for other atari games? Or do I need to change it for other games? Also the original references are very welcome, thank you very much.

Thanks.

**Comment by ikostrikov** [comment]
Hi,

it's just a standard way to initialize parameters. As far as I can remember, I took it from OpenAI's universe starter code.

It should work for other games as well.

**Comment by zhengsx** [comment]
Haha, thank you very much.

Btw, the number is indeed magic, if I don’t use that initialization, the Pong can converge but much more slow( 1M steps v.s. 3.5M steps)

**Comment by ikostrikov** [comment]
Yeah, RL is extremely unstable wrt different hyper parameters.
