### ISSUE TITLE
Mixture of model prediction and update

### ISSUE THREAD

**Issue by dohnala** [ikostrikov/pytorch-a3c#42]
Hello Ilya,

first, thanks for you amazing work. I would have one question about a way how you have designed an A3C training.

What you basically do is that you play N steps and you store all the values, log_probs and entropies during this phase and you store all these variables in lists. After that, you perform an update, where you use these variables.

Another approach would be to split this into two methods:
 - predict(state), which would return action values
 - update(states, actions, rewards), which would update the model

In this setup, you can use volatile=True in predict, but on the other hand, in update method you have to compute all these values, log_probs and entropies by forward pass on all the states.

My question is, did you consider this second approach? Why did you chose the first one? Is it more efficient or its just simpler to implement? I am trying to make my own A3C implementation and definitely I will try out myself which is more efficient, but I am curious about your opinion.

Thanks

**Comment by ikostrikov** [comment]
The first approach is faster on CPU in practice (no need to do a second pass, no performance gain from using batches).

However, the second one can be faster for GPU training. I implemented the second approach here:
https://github.com/ikostrikov/pytorch-a2c-ppo-acktr

**Comment by dohnala** [comment]
Thanks, that seems to be reasonable. Currently, I am using Macbook Pro with i7 processor with 4 cores and I don't have any GPU available so that's why I am trying experimenting with A3C. I will try to implement first approach. Also, is it possible to use PPO algorithm with this asynchronous settings? I didn't read about PPO much and just wonder if it is possible. Also do you think PyTorch is good fit for implementing CPU reinforcement algorithms or are there any better? I like the way how PyTorch works and is easy to use.

**Comment by ikostrikov** [comment]
4 cores is fine for mujoco but not enough for atari (unless you are ready to wait for several days to get results).

Synchronous methods are much easier to debug and they usually perform just as well as asynchronous methods. See the OpenAI blogpost about a2c/acktr where they mention that.

In terms of the frameworks, the difference between all the frameworks nowadays is marginal (in terms of time you need to spend in different frameworks to implement exactly the same thing). It's usually +-1-2 hours between TensorFlow and PyTorch depending on a specific task. But PyTorch tends to work slightly faster than TensorFlow, especially on CPU. So if performance is the major concern then I would recommend PyTorch.

**Comment by dohnala** [comment]
Thanks for you time, it helps a lot. I will not use Atari nor Mujoco. I am trying to implement my own environment based on descrete grid and experiment with it, so hopefully my processor is enough.
