### ISSUE TITLE
GPU version of a3c algorithm?

### ISSUE THREAD

**Issue by bearpaw** [ikostrikov/pytorch-a3c#44]
Hi,

Thanks for the code. I was wondering if there is a GPU version of the A3C algorithm in PyTorch. I notice that the hogwild! example in PyTorch is the CPU version.

For your reference, I've found a GPU version of A3C in tensorflow: https://github.com/caomw/icra2017-visual-navigation

**Comment by ikostrikov** [comment]
Hi,

A3C is designed specifically to be efficient on CPU.

A2C can be more efficient on GPU:
https://github.com/ikostrikov/pytorch-a2c-ppo-acktr

**Comment by bearpaw** [comment]
I got it. Thank you very much!
