### ISSUE TITLE
Why is the convergence on Pong so fast?

### ISSUE THREAD

**Issue by Omegastick** [ikostrikov/pytorch-a3c#56]
It takes about 15 minutes to converge on Pong with this repo. The [A3C Paper](https://arxiv.org/pdf/1602.01783.pdf) managed to get convergence with 16 workers in about 4 hours. That's a speedup of 16x!

I'm aware that there are a few improvements such as GAE and normalising the observations from Gym, but those shouldn't account for a 16x speedup.

I've been trying to replicate those results in my own project, but can't seem to get better than 3-4 hours for convergence. Is there some kind of trick I'm missing?

**Comment by ikostrikov** [comment]
DeepMind didn't open source their implementation so it's nearly impossible to reproduce the exact results.

RL is extremely sensitive to hyper parameters (see https://arxiv.org/abs/1709.06560).

Actually, probably other tasks get worse results and DM original code was tuned to work better in average.
