### ISSUE TITLE
Does this implementation solve the inconsistent parameter issue from the original TF universe-starter-agent implementation?

### ISSUE THREAD

**Issue by ethancaballero** [ikostrikov/pytorch-a3c#6]
I'm referencing this issue:
https://github.com/tensorflow/tensorflow/issues/6360#issuecomment-271486091

**Comment by ikostrikov** [comment]
I'm not sure. Probably, we should ask authors of PyTorch.

But is it a big issue? I thought that original A3C doesn't use locking so parameters might be inconsistent.

**Comment by ethancaballero** [comment]
@apaszke

**Comment by apaszke** [comment]
@ethancaballero please don't tag me all over GitHub. I'm not the only person who can answer this quesition. If you still have doubts ask on the forums.
