### ISSUE TITLE
Does this implementation work with real-time environments that lag such as VNC environments from universe?

### ISSUE THREAD

**Issue by ethancaballero** [ikostrikov/pytorch-a3c#8]
Have you tested this implementation on any Universe environments that lag due to the VNC?
The original one had a separate thread used for collecting experience that runs in parallel to optimization (I guess to make up for the lag?):
https://github.com/openai/universe-starter-agent/issues/36#issuecomment-268913461

Does this one have a separate thread used for collecting experience that runs in parallel to optimization?

**Comment by ikostrikov** [comment]
No, I tested only on the standard environments. And the moment it doesn't collect experience in a separate thread.
